### ISSUE TITLE
Broken build with capstone 5.0

### ISSUE THREAD

**Issue by patryk4815** [eteran/edb-debugger#839]
Broken build with capstone 5.0

Error:
```
/build/source/src/capstone-edb/Instruction.cpp: In function 'bool CapstoneEDB::is_SIMD_PD(const Operand&)':
/build/source/src/capstone-edb/Instruction.cpp:882:14: error: 'X86_INS_VCVTPD2DQX' was not declared in this scope; did you mean 'X86_INS_VCVTPD2DQ'?
  882 |         case X86_INS_VCVTPD2DQX: // FIXME: what's this?
      |              ^~~~~~~~~~~~~~~~~~
      |              X86_INS_VCVTPD2DQ
/build/source/src/capstone-edb/Instruction.cpp:883:14: error: 'X86_INS_VCVTPD2PSX' was not declared in this scope; did you mean 'X86_INS_VCVTPD2PS'?
  883 |         case X86_INS_VCVTPD2PSX: // FIXME: what's this?
      |              ^~~~~~~~~~~~~~~~~~
      |              X86_INS_VCVTPD2PS
```
 `FIXME: what's this?`?

**Comment by eteran** [comment]
Issue was fixed 6 years ago. Please try with a newer version of edb, ideally the master branch.

**Comment by patryk4815** [comment]
thanks! Please release new version :)
