### ISSUE TITLE
Build on Ubuntu 15.04 issue.

### ISSUE THREAD

**Issue by losywee** [eteran/edb-debugger#213]
1. System environment:
gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13)
QMake version 3.0
Using Qt version 5.5.0 in /opt/Qt/5.5/gcc_64/lib

2. Error output:
```bash
capstone-edb/Instruction.cpp: In member function ‘void CapstoneEDB::Instruction::fillPrefix()’:
capstone-edb/Instruction.cpp:71:18: error: ‘X86_PREFIX_LOCK’ is not a member of ‘CapstoneEDB::Capstone’
  if(prefixes[0]==Capstone::X86_PREFIX_LOCK)
                  ^
capstone-edb/Instruction.cpp:73:18: error: ‘X86_PREFIX_REP’ is not a member of ‘CapstoneEDB::Capstone’
  if(prefixes[0]==Capstone::X86_PREFIX_REP)
                  ^
capstone-edb/Instruction.cpp:75:18: error: ‘X86_PREFIX_REPNE’ is not a member of ‘CapstoneEDB::Capstone’
  if(prefixes[0]==Capstone::X86_PREFIX_REPNE)
                  ^
capstone-edb/Instruction.cpp:78:18: error: ‘X86_PREFIX_ES’ is not a member of ‘CapstoneEDB::Capstone’
  if(prefixes[1]==Capstone::X86_PREFIX_ES)
                  ^
capstone-edb/Instruction.cpp:80:18: error: ‘X86_PREFIX_CS’ is not a member of ‘CapstoneEDB::Capstone’
  if(prefixes[1]==Capstone::X86_PREFIX_CS)
                  ^
capstone-edb/Instruction.cpp:82:18: error: ‘X86_PREFIX_SS’ is not a member of ‘CapstoneEDB::Capstone’
  if(prefixes[1]==Capstone::X86_PREFIX_SS)
                  ^
capstone-edb/Instruction.cpp:84:18: error: ‘X86_PREFIX_DS’ is not a member of ‘CapstoneEDB::Capstone’
  if(prefixes[1]==Capstone::X86_PREFIX_DS)
                  ^
capstone-edb/Instruction.cpp:86:18: error: ‘X86_PREFIX_FS’ is not a member of ‘CapstoneEDB::Capstone’
  if(prefixes[1]==Capstone::X86_PREFIX_FS)
                  ^
capstone-edb/Instruction.cpp:88:18: error: ‘X86_PREFIX_GS’ is not a member of ‘CapstoneEDB::Capstone’
  if(prefixes[1]==Capstone::X86_PREFIX_GS)
                  ^
capstone-edb/Instruction.cpp:91:18: error: ‘X86_PREFIX_OPSIZE’ is not a member of ‘CapstoneEDB::Capstone’
  if(prefixes[2]==Capstone::X86_PREFIX_OPSIZE)
                  ^
capstone-edb/Instruction.cpp:93:18: error: ‘X86_PREFIX_ADDRSIZE’ is not a member of ‘CapstoneEDB::Capstone’
  if(prefixes[3]==Capstone::X86_PREFIX_ADDRSIZE)
                  ^
capstone-edb/Instruction.cpp: In constructor ‘CapstoneEDB::Instruction::Instruction(const void*, const void*, uint64_t, const std::nothrow_t&)’:
capstone-edb/Instruction.cpp:150:22: error: ‘cs_disasm’ is not a member of ‘CapstoneEDB::Capstone’
     if(first<last && Capstone::cs_disasm(csh, codeBegin, codeEnd-codeBegin-1, rva, 1, &insn))
                      ^
capstone-edb/Instruction.cpp:176:17: error: invalid conversion from ‘unsigned int’ to ‘CapstoneEDB::Operand::Register {aka CapstoneEDB::Capstone::x86_reg}’ [-fpermissive]
     operand.reg_=ops[i].reg;
                 ^
capstone-edb/Instruction.cpp:201:19: error: ‘CapstoneEDB::Capstone::cs_x86_op’ has no member named ‘size’
     switch(ops[i].size)
                   ^
capstone-edb/Instruction.cpp:211:19: error: ‘CapstoneEDB::Capstone::cs_x86_op’ has no member named ‘size’
     switch(ops[i].size)
                   ^
capstone-edb/Instruction.cpp: In member function ‘bool CapstoneEDB::Instruction::is_return() const’:
capstone-edb/Instruction.cpp:454:46: error: ‘X86_GRP_RET’ is not a member of ‘CapstoneEDB::Capstone’
  return Capstone::cs_insn_group(csh, &insn_, Capstone::X86_GRP_RET);
                                              ^
capstone-edb/Instruction.cpp: In member function ‘bool CapstoneEDB::Instruction::is_jump() const’:
capstone-edb/Instruction.cpp:480:68: error: invalid conversion from ‘const cs_insn* {aka const CapstoneEDB::Capstone::cs_insn*}’ to ‘CapstoneEDB::Capstone::cs_insn*’ [-fpermissive]
  return Capstone::cs_insn_group(csh, &insn_, Capstone::X86_GRP_JUMP);
                                                                    ^
In file included from ../src/capstone-edb/include/Instruction.h:31:0,
                 from capstone-edb/Instruction.cpp:18:
/usr/include/capstone/capstone.h:358:6: note: initializing argument 2 of ‘bool CapstoneEDB::Capstone::cs_insn_group(CapstoneEDB::Capstone::csh, CapstoneEDB::Capstone::cs_insn*, unsigned int)’
 bool cs_insn_group(csh handle, cs_insn *insn, unsigned int group_id);
      ^
capstone-edb/Instruction.cpp: In member function ‘bool CapstoneEDB::Instruction::is_return() const’:
capstone-edb/Instruction.cpp:455:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:6821: recipe for target '.release-shared/obj/Instruction.o' failed
make[1]: *** [.release-shared/obj/Instruction.o] Error 1
make[1]: Leaving directory '/tmp/edb-debugger/src'
Makefile:43: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2
```

**Comment by losywee** [comment]
Does I should install the X32 compatibly?

**Comment by eteran** [comment]
The latest version of edb requires Capstone version 3.0 or greater. Please ensure that this is installed.

**Comment by losywee** [comment]
Yes, I have installed the Capstone 3.0, but it shows the same error message.

**Comment by 10110111** [comment]
I've just built EDB successfully on Kubuntu 15.04 amd64. I've installed Capstone 3.0.4 into `$HOME/opt/capstone` and run qmake like this (retyping here from QEMU, might have typos):

    qtchooser -qt=5 -run-tool=qmake PREFIX=$HOME/opt/edb -recursive QMAKE_CXXFLAGS+="-I$HOME/opt/capstone/usr/include" QMAKE_LFLAGS+="-L$HOME/opt/capstone/usr/lib"

and then `make` finished without errors.

What were your steps?

**Comment by eteran** [comment]
@losywee any luck? Were you able to build edb? Perhaps it is worth trying with the latest version of capstone?

**Comment by krissrex** [comment]
Hi, I just successfully built edb (commit: afb4fd9386768106125563b896d8e5b2878884a3 ) on Ubuntu 15.04.

Here is how:

## Install dependencies

    sudo apt-get install qt5-default 
    sudo apt-get install libqt5xmlpatterns5-dev 
    sudo apt-get install libboost-math-dev 

### Install capstone

Using <code>apt-get</code> gives you version 2 as of now.
First, download source:
[downloads page](http://www.capstone-engine.org/download.html) did not have for Ubuntu 15, so I downloaded source from github:   
* [3.0.3.zip](https://github.com/aquynh/capstone/archive/3.0.3.zip).

Unzip to a folder, and open a terminal in there. Then run:

    make
    sudo make install

I kept the source folder in downloads. 

## Building

Now navigate to *edb source code*, which I downloaded with

    git clone --recursive git@github.com:eteran/edb-debugger.git

Run <code>qmake</code> as suggested by @10110111 , but with the paths altered. My source is in <code>/home/krissrex/Downloads/capstone-3.0.3/include</code>, and the previous <code>sudo make install</code> installed capstone binaries to <code>/usr/lib/</code>.
Then run <code>make</code>

    qmake -recursive QMAKE_CXXFLAGS+="-I$HOME/home/krissrex/Downloads/capstone-3.0.3/include" QMAKE_LFLAGS+="-L$HOME/usr/lib"
    make

## Installing

Like advertised, you use <code>make install</code>:

    sudo make install

## Running

    edb

**Comment by 10110111** [comment]
> qmake -recursive QMAKE_CXXFLAGS+="-I$HOME/home/krissrex/Downloads/capstone-3.0.3/include" QMAKE_LFLAGS+="-L$HOME/usr/lib"

`$HOME` here is extraneous: the result for `LFLAGS` is like this: `-L/home/krissrex/usr/lib`, which I think is not what you wanted.
In fact, since you've installed capstone, it should have been installed in the default directories, so you shouldn't have to specify special flags to qmake.

**Comment by krissrex** [comment]
@10110111 Thanks, I will retry and edit my post. As now now, I am getting 

    *** stack smashing detected ***: edb terminated
when trying to open a file in edb. Not sure if it is related to my build process.

**Comment by 10110111** [comment]
It's an interesting bug. Please create a separate issue for this, and also give backtrace of this crash.

**Comment by krissrex** [comment]
@10110111 The corrected qmake fixed the stack smashing bug. My comment has been updated. Thank you.

**Comment by eteran** [comment]
Great, I will close this issue then.

Thanks!
