### ISSUE TITLE
How to do with this when I 'make' it on Ubuntu14.04

### ISSUE THREAD

**Issue by qianfei11** [eteran/edb-debugger#668]
```
/home/xxx/edb-debugger/src/DataViewInfo.cpp: In constructor ‘DataViewInfo::DataViewInfo(const std::shared_ptr<IRegion>&)’:
/home/xxx/edb-debugger/src/DataViewInfo.cpp:27:83: error: ‘make_unique’ is not a member of ‘std’
 DataViewInfo::DataViewInfo(const std::shared_ptr<IRegion> &r) : region(r), stream(std::make_unique<RegionBuffer>(r)) {
                                                                                   ^
/home/xxx/edb-debugger/src/DataViewInfo.cpp:27:112: error: expected primary-expression before ‘>’ token
 DataViewInfo::DataViewInfo(const std::shared_ptr<IRegion> &r) : region(r), stream(std::make_unique<RegionBuffer>(r)) {
                                                                                                                ^
make[2]: *** [src/CMakeFiles/edb.dir/DataViewInfo.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/edb.dir/all] Error 2
make: *** [all] Error 2
```

I have no idea...

**Comment by 10110111** [comment]
What compiler do you use?

**Comment by eteran** [comment]
Does adding:

    #include <memory>

to the top of that file make it compile?

**Comment by 10110111** [comment]
@eteran If that could help, we'd have an error earlier, in the declaration of `stream` member pointer; anyway, the header already does include `<memory>`.
Here it looks like the problem is that either the compiler is too old to support `std::make_unique`, or the file is for some reason compiled in C++11 mode.

**Comment by eteran** [comment]
@10110111  Yea, I agree. Just kinda waking up and it was the first thing which came to mind.

**Comment by qianfei11** [comment]
@10110111 I use `gcc --version` and it tells me 'gcc 4.8.4'. Should I upgrade it?

**Comment by eteran** [comment]
@qianfei11 edb has been tested to build correctly with gcc >= 4.5. So yes, if possible, please upgrade.

**Comment by qianfei11** [comment]
@eteran I already update it but it does not work.
```
xxx@ubuntu:~/edb-debugger/build$ make
[  1%] Automatic MOC and UIC for target edb
[  1%] Built target edb_autogen
[  1%] Building CXX object src/CMakeFiles/edb.dir/DataViewInfo.cpp.o
/home/xxx/edb-debugger/src/DataViewInfo.cpp: In constructor ‘DataViewInfo::DataViewInfo(const std::shared_ptr<IRegion>&)’:
/home/xxx/edb-debugger/src/DataViewInfo.cpp:27:83: error: ‘make_unique’ is not a member of ‘std’
 DataViewInfo::DataViewInfo(const std::shared_ptr<IRegion> &r) : region(r), stream(std::make_unique<RegionBuffer>(r)) {
                                                                                   ^
/home/xxx/edb-debugger/src/DataViewInfo.cpp:27:112: error: expected primary-expression before ‘>’ token
 DataViewInfo::DataViewInfo(const std::shared_ptr<IRegion> &r) : region(r), stream(std::make_unique<RegionBuffer>(r)) {
                                                                                                                ^
make[2]: *** [src/CMakeFiles/edb.dir/DataViewInfo.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/edb.dir/all] Error 2
make: *** [all] Error 2
xxx@ubuntu:~/edb-debugger/build$ gcc --version
gcc-6 (Ubuntu 6.4.0-17ubuntu1~14.04) 6.4.0 20180424
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by eteran** [comment]
@qianfei11 a quirk of cmake is that it retains the compiler information even when you re-run it on an existing build directory.

Please try deleting the build directory entirely, and starting a fresh build.

**Comment by eteran** [comment]
Notice this line:

`The CXX compiler identification is GNU 4.8.5`

Try this:

    rm -rf build/
    mkdir build
    cd build
    CXX=g++ cmake ..
    make

**Comment by qianfei11** [comment]
@eteran It works. I tried in another way:
```
...
xxx@ubuntu:~/edb-debugger/build$ export CC=/usr/bin/gcc-6
xxx@ubuntu:~/edb-debugger/build$ export CXX=/usr/bin/g++-6
xxx@ubuntu:~/edb-debugger/build$ cmake ..
-- The CXX compiler identification is GNU 6.4.0
...
[100%] Built target DebuggerErrorConsole
```
