### ISSUE TITLE
Will not compile on Ubuntu 8.04

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eteran/edb-debugger#63]
```
$ qmake
$ make
(...)
g++ -Wl,--no-undefined -shared -o libSessionManager.so SessionManager.o 
moc_SessionManager.o   -L/usr/lib -lQtGui -lQtCore -lpthread 

SessionManager.o: In function `SessionManager::privateInit()':
~/debugger/plugins/SessionManager/SessionManager.cpp:29: undefined reference to 
`edb::v1::setSessionFileHandler(SessionFileInterface*)'

$ gcc --version
gcc (GCC) 4.2.4 (Ubuntu 4.2.4-1ubuntu4)
```

Original issue reported on code.google.com by `evan.teran` on 3 Oct 2012 at 3:21
